---
output:
  html_notebook: 
    css: www/bootstrap.css
  html_document:
    code_folding: hide
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
library(shiny)
```

```{r Internal functions}
display.func <- function(input)
{
  if (input$law == "Uniform") 
    x <- runif(input$data)
  else
    x    <- rnorm(input$data)
  bins <- seq(min(x), max(x), length.out = input$bins + 1)
  hist(x, breaks = bins, 
       col = c("blue","red","green")[as.numeric(input$color)],
       border = c("black","orange","pink")[as.numeric(input$border)],
       xlab = "Simulated values",
       main = input$title)
}
```

```{r User-Interface}
ui <- fluidPage(theme="bootstrap.css",
                
  titlePanel("Histogram"),
  
  # Layout with a bar (left) and a graphic page (center)
  sidebarLayout(
    
    # Side Bar
    sidebarPanel(
      radioButtons("law", "Distribution Law",inline=TRUE,choices=c("Uniform","Normal")),
      sliderInput(inputId = "data", label = "Number of Data:", 
                  min = 1, max = 1000,  value = 200),
      sliderInput(inputId = "bins", label = "Number of Classes:", 
                  min = 1, max = 200,  value = 100),
      selectInput("color", label = "Bin Color", 
                  choices = list("blue" = 1, "red" = 2, "green" = 3), 
                  selected = 1),
      selectInput("border", label = "Border Color", 
                  choices = list("black" = 1, "orange" = 2, "pink" = 3), 
                  selected = 1),
      textInput("title", label = "Graphic title", value = "Histogram")
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      plotOutput(outputId = "histPlot")
    )
  )
)
```


```{r Server Part}
server <- shinyServer(function(input, output, session) 
{
  output$histPlot <- renderPlot({display.func(input)})
})
```

```{r Launching application}
shinyApp(ui=ui,server=server, options = list(width = "100%", height = 800))
```
